version: '3'

services:
  db:
    image: postgres:15.4
    restart: always
    ports:
      ["5400:5432"]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: outletpassiondb
    volumes:
      - ./postgres:/var/lib/postgresql/data